#!/bin/bash

BASE_URL="http://localhost:8080/api/v2/auth/sign-up"

names=(
"James Smith"
"Mary Johnson"
"Robert Williams"
"Patricia Brown"
"John Jones"
"Jennifer Garcia"
"Michael Miller"
"Linda Davis"
"William Rodriguez"
"Elizabeth Martinez"
"David Hernandez"
"Barbara Lopez"
"Richard Gonzalez"
"Susan Wilson"
"Joseph Anderson"
"Jessica Thomas"
"Thomas Taylor"
"Sarah Moore"
"Charles Jackson"
"Karen Martin"
"Christopher Lee"
"Nancy Perez"
"Daniel Thompson"
"Lisa White"
"Matthew Harris"
"Betty Sanchez"
"Anthony Clark"
"Sandra Ramirez"
"Mark Lewis"
"Ashley Robinson"
"Donald Walker"
"Kimberly Young"
"Steven Allen"
"Emily King"
"Paul Wright"
"Donna Scott"
"Andrew Torres"
"Michelle Nguyen"
"Joshua Hill"
"Dorothy Flores"
"Kenneth Green"
"Carol Adams"
"Kevin Nelson"
"Amanda Baker"
"Brian Hall"
"Melissa Rivera"
"George Campbell"
"Deborah Mitchell"
"Edward Carter"
"Stephanie Roberts"
"Ronald Gomez"
"Rebecca Phillips"
"Timothy Evans"
"Laura Turner"
"Jason Diaz"
"Sharon Parker"
"Jeffrey Cruz"
"Cynthia Edwards"
"Ryan Collins"
"Amy Stewart"
"Jacob Morris"
"Angela Rogers"
"Gary Reed"
"Anna Cook"
"Nicholas Morgan"
"Brenda Bell"
"Eric Murphy"
"Pamela Bailey"
"Jonathan Cooper"
"Nicole Richardson"
"Stephen Cox"
"Samantha Howard"
"Larry Ward"
"Katherine Peterson"
"Justin Gray"
"Christine Ramirez"
"Scott James"
"Olivia Watson"
"Brandon Brooks"
"Victoria Kelly"
"Benjamin Sanders"
"Grace Price"
"Samuel Bennett"
"Hannah Wood"
"Gregory Barnes"
"Natalie Ross"
"Frank Henderson"
"Chloe Coleman"
"Patrick Jenkins"
"Zoe Perry"
"Raymond Powell"
"Lily Long"
"Jack Patterson"
"Sophia Hughes"
"Dylan Flores"
"Avery Washington"
"Nathan Butler"
"Evelyn Simmons"
"Aaron Foster"
"Scarlett Bryant"
"Christian Alexander"
"Madison Russell"
)

echo "Creating ${#names[@]} users..."
echo

for i in "${!names[@]}"; do
    name="${names[$i]}"
    email=$(echo "$name" | tr '[:upper:]' '[:lower:]' | tr ' ' '.')"$i@example.com"

    status=$(curl -s -o /dev/null -w "%{http_code}" \
      -X POST "$BASE_URL" \
      -H "Content-Type: application/json" \
      -d "{
        \"name\": \"$name\",
        \"email\": \"$email\",
        \"password\": \"P@ssw0rd\"
      }")

    echo "[$((i + 1))/${#names[@]}] $status - $email"
done

echo
echo "Done."