basePath: /api
definitions:
  model.ErrorResponse:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
  model.SignUpRequest:
    properties:
      email:
        maxLength: 100
        type: string
      name:
        maxLength: 100
        minLength: 2
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  model.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
  description: Backend API
  title: Backend API
  version: "1.0"
paths:
  /v1/auth/sign-up:
    post:
      consumes:
      - application/json
      description: Create new user account
      parameters:
      - description: Sign Up Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Sign up
      tags:
      - Auth
swagger: "2.0"
