server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/sandbox_db}
    username: ${JDBC_DATABASE_USERNAME:sandbox}
    password: ${JDBC_DATABASE_PASSWORD:sandbox}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  lifecycle:
    timeout-per-shutdown-phase: 30s

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      UserEmailUnique: USER_EMAIL_UNIQUE

springdoc:
  pathsToMatch: /, /api/**

jwt:
  secret-key: ${JWT_SECRET_KEY:SecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKey}
  exp-time-ms: ${JWT_EXP_TIME_MS:86400000}  # 24 hours

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}