vite/create:
	pnpm create vite frontend-react-ts --template react-ts

vite/dep:
	pnpm install react-router @tanstack/react-query axios js-cookie react-hot-toast zustand
	pnpm install -D @types/js-cookie 