// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "agussyahrilmubarok.github.io/backend/internal/application/dto"
	mock "github.com/stretchr/testify/mock"
)

// AuthUseCase is an autogenerated mock type for the AuthUseCase type
type AuthUseCase struct {
	mock.Mock
}

// SignIn provides a mock function with given fields: ctx, req
func (_m *AuthUseCase) SignIn(ctx context.Context, req dto.SignInRequest) (*dto.AuthResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 *dto.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.SignInRequest) (*dto.AuthResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.SignInRequest) *dto.AuthResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.SignInRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignUp provides a mock function with given fields: ctx, req
func (_m *AuthUseCase) SignUp(ctx context.Context, req dto.SignUpRequest) (*dto.AuthResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 *dto.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.SignUpRequest) (*dto.AuthResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.SignUpRequest) *dto.AuthResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.SignUpRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthUseCase creates a new instance of AuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUseCase {
	mock := &AuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
