services:
  redis:
    image: redis:8.0.3
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sandbox_net

  redis-insight:
    image: redis/redisinsight:2.70
    container_name: redis-insight
    restart: on-failure
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/db
    networks:
      - sandbox_net
    depends_on:
      - redis

volumes:
  redis_data:
  redis_insight_data:

networks:
  sandbox_net:
    driver: bridge