app:
  name: web-go
  port: 3000
  timezone: Asia/Jakarta

database:
  host: localhost
  port: 5432
  user: sandbox
  password: sandbox
  dbname: sandbox_db
  sslmode: disable
  timezone: Asia/Jakarta

session:
  secret_key: "SecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKey"  
  max_age: 604800  # 7 day in ms
