app:
  name: web-go
  port: 8080
  timezone: Asia/Jakarta

database:
  host: localhost
  port: 5432
  user: sandbox
  password: sandbox
  dbname: sandbox_db
  sslmode: disable
  timezone: Asia/Jakarta

session:
  secret_key: "737461727465722f7765622d676f737461727465722f7765622d676f"  
  max_age: 604800  # 7 day in ms
