app:
  name: web-go
  port: 8080
  timezone: Asia/Jakarta

database:
  host: localhost
  port: 5432
  user: sandbox
  password: sandbox
  dbname: sandbox_db
  sslmode: disable
  timezone: Asia/Jakarta

session:
  secret_key: "bXlfc3VwZXJfc2VjcmV0X2tleV8zMmJ5dGVz"  
  max_age: 604800  # 7 day in ms
